### ISSUE TITLE
A better way to work with local collections.

### ISSUE THREAD

**Issue by ViktorKahu** [Bnyro/WallYou#111]
### Describe your suggested feature

1) I would like to be able to add and name local colections to the side menu along with the online collections already there.

2) I'd like to be able to add photos from local collection to favorites, and be able to "mix and match" with photos from the online collections.

Regards.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Wall You only serves the purpose of being a wallpaper app, what you're describing pretty much sounds like a gallery app.
If you want to mix local and online photos, you can download the online photos and move them into the same directory as your other photos, and submit that directory to the local wallpaper changer.
However, no plansdor that due to the given reasons.
